import streamlit as st
import random
import util.googleAPI as lms

st.set_page_config(page_title="Language Perfect", page_icon="📷")
st.title("Language Perfect")
st.write(
    """This page is a demo of Language Perfect. It is a tool that can
    help people learn language with a help of language model. There are number of modes of the app.
    Firstly, sentence translation. There will be number of sentences in the language that you choose. 
    You will have to translate that to english and submit, in which the model will tell you how well you did, and 
    a good example of the translation. Secondly, there is a vocabulary test. There will be number of words generated by the 
    AI, and you will have to translate them. Thirdly, there is a conversational AI. You can freely talk to the AI, and it will give
    two answers. Firstly, it will give you a response to whatever you said, it the chosen language. Secondly, it will give you
    feedback on what you said, such as any grammatical errors, or any words that you could have used instead. Enjoy!"""
)

col1, col2 = st.columns(2)

with col1:
    # Choose the language
    with open("const/languages_list.csv", "r") as f:
        languages = []
        for line in f:
            if line.strip() != "English":
                languages.append(line.strip())

    language = st.selectbox("Select the language:", languages)

    # Choose your level 
    level = st.selectbox("Select your level:", ("Beginner", "Intermediate", "Advanced"))

    # Choose the mode
    mode = st.selectbox("Select the mode:", ("Sentence Translation", "Vocabulary Test", "Conversational AI"))

    if mode == "Sentence Translation":
        # Choose the number of sentences
        num = st.slider("Select the number of sentences:", 1, 10, 5)
        start = st.button("Start", key = "start_sentence_translation")
    elif mode == "Vocabulary Test":
        # Choose the number of words
        words = st.slider("Select the number of words:", 1, 10, 5)
        start = st.button("Start", key = "start_vocabulary_test")

with col2:
    if mode == "Sentence Translation" and start:
        sentences = lms.get_sentence(language, level, num)
        sentences = sentences.split("\n")

        for i in range(num):
            sentence = sentences[i]
            st.write(sentence)

    elif mode == "Vocabulary Test":
        # Choose the number of words
        words = st.slider("Select the number of words:", 1, 10, 5)

if mode=="Sentence Translation" and start:
    st.write("Enter your translation below. Format it as '1. Translation for sentence 1', '2. Translation for sentence 2', etc.")
    translation = st.text_area("Enter your translation:")

    print("What")
    submit_translation = st.button("Submit", key = f"{sentences}_submission")

    while not submit_translation:
        continue
    
    if submit_translation:
        print("asdf?")
        evaluation = lms.evaluate_translation(sentences, translation, language, level)
        st.success(evaluation)
