import streamlit as st
import random
import util.chatAPI as lms

st.set_page_config(page_title="Generative AI Detector", page_icon="🕵️")
st.title("Generative AI Detector")
st.write(
    """This page is a demo of the Generative AI Detector. It is a tool that can
    detect whether a text is generated by an AI or not. It will fetch some suspicious lines
    that may be generated by an AI."""
)

# Age input (Age is important factor)
age = st.slider("Select the writer's age:", 0, 100, 18)

# Text Input
text_input = st.text_area("Enter suspicious text:")

# Submit Button
if st.button("Submit"):
    if age and text_input:
        detect_result = lms.analyze_suspicious_lines(age, text_input)
        st.success(detect_result)
    else:
        st.warning("Please enter some text.")